name: Simple Logging Workflow

# This determines when the workflow runs
on: [push]

jobs:
  say-hello:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      - name: Log Greeting
        run: echo "Hello World!"
